<template>
  <div class="fullLoader scrollVertical scrollbar">
    <loader v-show="pageLoader" class="w-100"></loader>
    <div class="signupContent">
      <div class="row h-100 justify-content-center">
        <div class="col-12 col-md-9 col-lg-8 col-xl-7 col-xxl-6 col-xxxl-5">
          <img src="/assets/website/images/logo.svg" alt="Logo" class="loginLogo d-block text-center pb-0 pb-sm-4 pt-0" width="240" />
          <div class="authSteps p-0">
              <div class="head text-center mb-4 mb-md-5 mt-3 mt-sm-0">
                <h2 class="pt-0 pt-xl-3">Enable Two-Factor Authentication </h2>
                <p>Verify your Registration and keep your account safe with three quick steps </p>
              </div>
              <div class="twoauthSteps">
                <div class="d-flex border-bottom mb-4 pb-4 twoauthStepsInner">
                  <div class="ico">
                    <img src="/assets/website/images/google-authenticator.png" alt="Authenticator APP" />
                  </div>
                  <div class="desc text-left">
                    <h5 class="mb-1">Download an Authenticator App</h5>
                    <p class="mb-0">Download and install Authy or Google Authenticator to your phone or tablet </p>
                  </div>
                </div>
                <div class="d-flex border-bottom mb-4 pb-4 twoauthStepsInner">
                  <div class="ico">
                    <img :src="src_data" alt="Icon" />
                  </div>
                  <div class="desc text-left">
                    <h5 class="mb-1">Scan The QR Code</h5>
                    <p class="mb-0">Open the authentication app and scan the image to the left, using your phone's camera</p>
                  </div>
                </div>
                <div class="d-flex twoauthStepsInner">
                  <div class="ico">
                    <img src="/assets/website/images/otp4.svg" alt="IconAPP" />
                  </div>
                  <Form @submit="(mode == 'register') ? verifyQrCode() : submitCode()" ref="regform">
                    <div class="desc text-left">
                      <h5 class="mb-3">Log in with your Code</h5>
                      <p class="mb-3">Enter the 6-digit verification code generated by the authenticator and log into your new Capital Wallet account </p>
                      <div class="authenticator_input d-flex align-items-center">
                        <Field type="text" class="form-control authenticator_inputCode" id="" name="otp" placeholder=" " v-model="otp" rules="required" />
                        
                      </div>
                      <ErrorMessage name="otp" class="text-danger" />
                      <div class="mt-4">
                        <input type="submit" class="cap_btn large_btn border-0 authenticatorBtn" value="Verify and Sign In" :class="pageLoader ? 'disabled' : ''" />

                        <a href="#" class="cap_btn border-btn large_btn authenticatorBtn" @click.prevent="logout()">Sign Out</a>
                      </div>
                    </div>
                  </Form>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
  import * as types from "@/types";
  import { mapActions } from "vuex";
  import { Form, Field, ErrorMessage } from "vee-validate";
  export default {
    name: "two-FA",
    data() {
      return {
        pageLoader: false,
        src_data: "",
        code : '',
        otp : '',
        gAuthenticatorEnabled : '0'
      };
    },
    props:['emailFlag','passwordFlag','mode'],
    components: { Form, Field, ErrorMessage },
    methods: {
      logout() {
        localStorage.clear();
        window.location.replace("/")
      },
      ...mapActions({
        _runUserLogin2FA: types.RUN_USER_LOGIN_2FA
      }),
      submitCode() {
        if (this.pageLoader) {  return;  }
        const _that = this;
        let input_json = {
          globalParams: {
            google_token: _that.otp.toString(),
            email: _that.emailFlag,
            password: _that.passwordFlag,
          },
          localParams: {
            parameter: _that,
          },
        };
        _that._runUserLogin2FA(input_json);
      },

      //==========================register===============================================
      generateQrCode() {
        if (this.pageLoader) {  return;  }
        let input_json = {
          globalParams: {},
          localParams: { parameter: this },
        };
        this._runGenerate2FaQrcode(input_json);
      },
      verifyQrCode() {
        if (this.pageLoader) {  return;  }
        const _that = this;
        let input_json = {
          globalParams: {
            google_token: _that.otp.toString(),
            step: 1,
          },
          localParams: { parameter: _that},
        };
        _that._runVerify2FaQrcode(input_json);
      },
    },
    created() {
      if(this.mode == 'register'){
        this.gAuthenticatorEnabled =  this.get_user.profile.gAuthenticatorEnabled
        if (parseInt(this.get_user.profile.gAuthenticatorEnabled) == 0 || this.get_user.profile.gAuthenticatorEnabled == null) {
          this.generateQrCode();
        }
      }else{
        this.src_data = this.fa_user_state.profile['2fa_data'];
        this.gAuthenticatorEnabled =  this.fa_user_state.profile.gAuthenticatorEnabled
      }
      
    }
  };
</script>