export class notificationConst {
  public static RUN_GET_NOTIFICATION_LIST: string ="/RUN_GET_NOTIFICATION_LIST";
  public static GET_NOTIFICATION_LIST: string = "/GET_NOTIFICATION_LIST";
  public static SET_NOTIFICATION_LIST: string = "/SET_NOTIFICATION_LIST";

  public static SET_UNREAD_NOTIFICATION_DATA: string = "/SET_UNREAD_NOTIFICATION_DATA";
  public static GET_UNREAD_NOTIFICATION_DATA: string = "/GET_UNREAD_NOTIFICATION_DATA";

  public static SET_READ_NOTIFICATION_DATA: string = "/SET_READ_NOTIFICATION_DATA";
  public static GET_READ_NOTIFICATION_DATA: string = "/GET_READ_NOTIFICATION_DATA";

  public static RUN_READ_UNREAD_NOTIFICATION = "/RUN_READ_UNREAD_NOTIFICATION";

  public static RUN_GET_ACTIVITY_LIST: string ="/RUN_GET_ACTIVITY_LIST";
  public static SET_ACTIVITY_LIST: string = "/SET_ACTIVITY_LIST";
  public static GET_ACTIVITY_LIST: string = "/GET_ACTIVITY_LIST";

  public static RUN_MARK_ACTIVITY_AS_READ: string ="/RUN_MARK_ACTIVITY_AS_READ";

  // public static RUN_NOTIFICATION_SETTINGS = "/RUN_NOTIFICATION_SETTINGS";
  // public static SET_NOTIFICATION_SETTINGS: string =
  //   "/SET_NOTIFICATION_SETTINGS";
  // public static GET_NOTIFICATION_SETTINGS: string =
  //   "/GET_NOTIFICATION_SETTINGS";

  // public static RUN_NOTIFICATION_GET_SETTINGS =
  //   "/RUN_NOTIFICATION_GET_SETTINGS";
  // public static SET_NOTIFICATION_GET_SETTINGS: string =
  //   "/SET_NOTIFICATION_GET_SETTINGS";
  // public static GET_NOTIFICATION_GET_SETTINGS: string =
  //   "/GET_NOTIFICATION_GET_SETTINGS";

  // public static RUN_NOTIFICATION_ENABLE_GET_SETTINGS =
  //   "/RUN_NOTIFICATION_ENABLE_GET_SETTINGS";
  // public static SET_NOTIFICATION_ENABLE_GET_SETTINGS: string =
  //   "/SET_NOTIFICATION_ENABLE_GET_SETTINGS";
  // public static GET_NOTIFICATION_ENABLE_GET_SETTINGS: string =
  //   "/GET_NOTIFICATION_ENABLE_GET_SETTINGS";
}
